import os
import sys
import fnmatch
import logging
import subprocess
from pathlib import Path
from typing import List, Dict, Any, Optional

logger = logging.getLogger("netsentry-client.blocker")

START_TAG = "# === NETSENTRY FILTER START ==="
END_TAG = "# === NETSENTRY FILTER END ==="


class HostsBlocker:
    """
    Manages local OS hosts file to null-route restricted domains.
    Runs with surgical markers to guarantee user's existing hosts are never corrupted.
    """

    def __init__(self, hosts_path: Optional[str] = None):
        if hosts_path:
            self.hosts_path = Path(hosts_path)
        else:
            if sys.platform == "win32":
                self.hosts_path = Path(r"C:\Windows\System32\drivers\etc\hosts")
            else:
                self.hosts_path = Path("/etc/hosts")

    def is_writable(self) -> bool:
        """Check if we have administrative permission to modify the hosts file."""
        try:
            if not self.hosts_path.exists():
                return False
            with open(self.hosts_path, "a") as f:
                pass
            return True
        except PermissionError:
            return False
        except Exception:
            return False

    def sync_blocked_domains(self, blocked_patterns: List[str]) -> bool:
        """
        Updates the hosts file with blocked domain mappings to 0.0.0.0.
        Removes existing NETSENTRY section and replaces it with fresh rules.
        """
        if not self.is_writable():
            logger.warning(
                "Hosts file is not writable (Administrator privileges required to enforce hosts null-routing). "
                "Monitoring and socket-level alerts remain active."
            )
            return False

        try:
            content = ""
            if self.hosts_path.exists():
                with open(self.hosts_path, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()

            # Strip existing NETSENTRY block if present
            if START_TAG in content and END_TAG in content:
                before = content.split(START_TAG)[0]
                after = content.split(END_TAG)[1]
                content = before.rstrip() + "\n" + after.lstrip()

            # Build new block
            if blocked_patterns:
                lines = [
                    "",
                    START_TAG,
                    "# Auto-generated by NETSENTRY Network Defense Subsystem",
                    "# Prohibits restricted web access even across VPN tunnels",
                ]
                expanded_domains = set()
                for pat in blocked_patterns:
                    clean = pat.strip().lower()
                    if clean.startswith("*."):
                        base = clean[2:]
                        expanded_domains.add(base)
                        expanded_domains.add(f"www.{base}")
                    elif not clean.startswith("*"):
                        expanded_domains.add(clean)
                        if not clean.startswith("www."):
                            expanded_domains.add(f"www.{clean}")

                for dom in sorted(expanded_domains):
                    lines.append(f"0.0.0.0 {dom}")
                    lines.append(f"::1 {dom}")

                lines.append(END_TAG)
                lines.append("")

                new_content = content.rstrip() + "\n" + "\n".join(lines)
            else:
                new_content = content

            with open(self.hosts_path, "w", encoding="utf-8") as f:
                f.write(new_content)

            # Flush DNS resolver cache on Windows
            if sys.platform == "win32":
                subprocess.run(
                    ["ipconfig", "/flushdns"],
                    capture_output=True,
                    timeout=3,
                    creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
                )

            logger.info(f"Synchronized {len(blocked_patterns)} blocked domain rules to system hosts file.")
            return True

        except Exception as e:
            logger.error(f"Failed to update hosts file: {e}")
            return False

    def clear_all_blocks(self) -> bool:
        """Removes all NETSENTRY entries from hosts file on cleanup."""
        return self.sync_blocked_domains([])


class VpnDisarmer:
    """
    Detects and restricts VPN tunnels when strict lab/school anti-circumvention is enabled.
    """

    KNOWN_VPN_PROCESSES = [
        "wireguard.exe",
        "openvpn.exe",
        "openvpn-gui.exe",
        "nordvpn.exe",
        "protonvpn.exe",
        "expressvpn.exe",
        "tailscale.exe",
        "warp-svc.exe",
    ]

    @staticmethod
    def enforce_vpn_restriction(policy: Dict[str, Any], detected_vpns: List[Dict[str, str]]) -> List[str]:
        """
        If VPN policy prohibits tunnels and active VPN adapters/processes exist,
        attempts to terminate or disable them. Returns list of actions taken.
        """
        actions = []
        if not policy.get("block_all_vpns", True):
            return actions

        if detected_vpns:
            logger.warning(f"VPN circumvention detected! Adapters: {detected_vpns}")

        # Check and terminate known VPN processes if configured
        if policy.get("terminate_vpn_processes", True) and sys.platform == "win32":
            for proc_name in VpnDisarmer.KNOWN_VPN_PROCESSES:
                try:
                    res = subprocess.run(
                        ["taskkill", "/F", "/IM", proc_name],
                        capture_output=True,
                        text=True,
                        timeout=3,
                        creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
                    )
                    if res.returncode == 0:
                        msg = f"Terminated unauthorized VPN process: {proc_name}"
                        logger.warning(msg)
                        actions.append(msg)
                except Exception:
                    pass

        return actions
