import io
import csv
from datetime import datetime, timezone
from typing import List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether
from app.models.device import Device
from app.models.camera_session import CameraSession
from app.models.audit_log import AuditLog


def generate_devices_pdf(devices: List[Device], admin_username: str) -> io.BytesIO:
    """Generate a branded NETSENTRY Network Devices PDF Report."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    elements = []

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=6
    )
    sub_style = ParagraphStyle(
        'SubStyle',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=15
    )

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    elements.append(Paragraph("NETSENTRY - Local Network Device Inventory", title_style))
    elements.append(Paragraph(f"Generated on: {now_str} | Generated by: {admin_username} | Total Devices: {len(devices)}", sub_style))

    # Summary KPIs
    online_count = sum(1 for d in devices if d.status == "ONLINE")
    trusted_count = sum(1 for d in devices if d.trusted)
    client_count = sum(1 for d in devices if d.client_registered)

    kpi_data = [
        ["Total Devices", "Online Devices", "Trusted Devices", "Enrolled Clients"],
        [str(len(devices)), str(online_count), str(trusted_count), str(client_count)]
    ]
    kpi_table = Table(kpi_data, colWidths=[135, 135, 135, 135])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor("#f1f5f9")),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 15))

    # Device Table
    table_data = [["IP Address", "MAC Address", "Hostname", "Vendor", "Status", "Trust", "Client"]]
    for d in devices:
        table_data.append([
            d.ip_address,
            d.mac_address,
            (d.hostname[:20] + "...") if d.hostname and len(d.hostname) > 20 else (d.hostname or "N/A"),
            (d.vendor[:18] + "...") if d.vendor and len(d.vendor) > 18 else (d.vendor or "Unknown"),
            d.status,
            "Yes" if d.trusted else "No",
            "Enrolled" if d.client_registered else "None",
        ])

    table = Table(table_data, colWidths=[90, 105, 110, 105, 50, 40, 40])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
    ]))
    elements.append(table)

    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_camera_sessions_pdf(sessions: List[CameraSession], admin_username: str) -> io.BytesIO:
    """Generate a branded NETSENTRY Camera Access & Consent Audit Report."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    elements = []

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=6
    )
    sub_style = ParagraphStyle(
        'SubStyle',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=15
    )

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    elements.append(Paragraph("NETSENTRY - Consent-Based Camera Access Report", title_style))
    elements.append(Paragraph(f"Generated on: {now_str} | Generated by: {admin_username} | Total Sessions: {len(sessions)}", sub_style))

    approved_count = sum(1 for s in sessions if s.permission_status in ["APPROVED", "ACTIVE", "TERMINATED", "EXPIRED"])
    denied_count = sum(1 for s in sessions if s.permission_status == "DENIED")

    kpi_data = [
        ["Total Requests", "Approved / Active Sessions", "Explicitly Denied", "Default Duration Limit"],
        [str(len(sessions)), str(approved_count), str(denied_count), "10 Minutes"]
    ]
    kpi_table = Table(kpi_data, colWidths=[135, 135, 135, 135])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor("#f1f5f9")),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 15))

    table_data = [["Session ID", "Device ID", "Requested By", "Status", "Duration (s)", "Termination Reason"]]
    for s in sessions:
        table_data.append([
            s.session_uuid[:8],
            str(s.device_id),
            s.admin_username,
            s.permission_status,
            f"{s.session_duration_seconds:.1f}",
            s.termination_reason or "N/A",
        ])

    table = Table(table_data, colWidths=[80, 60, 100, 90, 80, 130])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
    ]))
    elements.append(table)

    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_devices_csv(devices: List[Device]) -> io.StringIO:
    """Generate CSV string of network devices."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["ID", "UUID", "IP Address", "MAC Address", "Hostname", "Vendor", "Status", "Trusted", "Client Registered", "First Seen", "Last Seen"])
    for d in devices:
        writer.writerow([
            d.id, d.device_uuid, d.ip_address, d.mac_address, d.hostname or "",
            d.vendor or "", d.status, d.trusted, d.client_registered,
            d.first_seen.isoformat(), d.last_seen.isoformat()
        ])
    output.seek(0)
    return output


def generate_audit_csv(logs: List[AuditLog]) -> io.StringIO:
    """Generate CSV string of audit logs."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["ID", "Timestamp (UTC)", "Actor", "Actor Type", "Event", "Device ID", "Device Name", "IP Address", "Status", "Metadata"])
    for l in logs:
        writer.writerow([
            l.id, l.timestamp.isoformat(), l.actor, l.actor_type, l.event,
            l.device_id or "", l.device_name or "", l.ip_address or "",
            l.status, l.metadata_json or ""
        ])
    output.seek(0)
    return output
